### ISSUE TITLE
Demo程序运行出错

### ISSUE THREAD

**Issue by joedan0104** [q4232134/AHibernate#1]
Demo程序运行时出错。注册Dao对象时发生错误，
错误日志信息如下：

05-08 15:49:09.201 15521-15527/com.jiaozhu.ahibernate I/art: Wrote stack traces to '/data/anr/traces.txt'
05-08 15:49:44.403 15521-15521/com.jiaozhu.ahibernate W/System.err: java.lang.IllegalAccessException: Class java.lang.Class<com.jiaozhu.ahibernate.util.DaoManager> cannot access protected  method void com.jiaozhu.demo.Dao.<init>(android.database.sqlite.SQLiteOpenHelper) of class java.lang.Class<com.jiaozhu.demo.Dao>
05-08 15:49:44.424 15521-15521/com.jiaozhu.ahibernate W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
05-08 15:49:44.446 15521-15521/com.jiaozhu.ahibernate W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
05-08 15:49:44.464 15521-15521/com.jiaozhu.ahibernate W/System.err:     at com.jiaozhu.ahibernate.util.DaoManager.registerDao(DaoManager.java:120)
05-08 15:49:44.481 15521-15521/com.jiaozhu.ahibernate W/System.err:     at com.jiaozhu.ahibernate.util.DaoManager.registerDao(DaoManager.java:109)
05-08 15:49:44.498 15521-15521/com.jiaozhu.ahibernate W/System.err:     at com.jiaozhu.demo.MainActivity.onClick(MainActivity.java:42)
05-08 15:49:44.510 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.view.View.performClick(View.java:5646)
05-08 15:49:44.525 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.view.View$PerformClick.run(View.java:22473)
05-08 15:49:44.539 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
05-08 15:49:44.553 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
05-08 15:49:44.567 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.os.Looper.loop(Looper.java:156)
05-08 15:49:44.582 15521-15521/com.jiaozhu.ahibernate W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
05-08 15:49:44.592 15521-15521/com.jiaozhu.ahibernate W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-08 15:49:44.608 15521-15521/com.jiaozhu.ahibernate W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
05-08 15:49:44.623 15521-15521/com.jiaozhu.ahibernate W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
05-08 15:49:52.388 15521-15528/? W/art: Debugger attempted to resume all threads without having suspended them all before.
05-08 15:49:52.390 15521-15521/? D/AndroidRuntime: Shutting down VM
05-08 15:49:52.402 15521-15528/? I/art: Debugger is no longer active
05-08 15:49:52.402 15521-15528/? I/art: Starting a blocking GC Instrumentation
05-08 15:49:52.410 15521-15521/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.jiaozhu.ahibernate, PID: 15521
                                                   java.util.NoSuchElementException: 指定表'Model'并未注册到DaoManager!
                                                       at com.jiaozhu.ahibernate.util.DaoManager.getDao(DaoManager.java:61)
                                                       at com.jiaozhu.ahibernate.util.DaoManager.getDaoByTable(DaoManager.java:74)
                                                       at com.jiaozhu.demo.MainActivity.onClick(MainActivity.java:43)
                                                       at android.view.View.performClick(View.java:5646)
                                                       at android.view.View$PerformClick.run(View.java:22473)
                                                       at android.os.Handler.handleCallback(Handler.java:761)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
05-08 15:49:52.510 15521-15521/? I/Process: Sending signal. PID: 15521 SIG: 9

**Comment by q4232134** [comment]
感谢提醒，现已修复。
manager.registerDao(Dao.class, ChildDao.class, Model.class);
将model类注册到manager就可以了
